name: project-manager

services:
    frontend:
        build:
            context: "./frontend"
            dockerfile: "frontend.Dockerfile"
        container_name: project-manager-frontend
        ports:
            - 5173:5173
        environment:
            - TZ=America/Toronto
        restart: unless-stopped
    backend:
        build:
            context: "./backend"
            dockerfile: "backend.Dockerfile"
        container_name: project-manager-backend
        ports:
            - 3001:3001
        environment:
            - NODE_ENV=docker
            - TZ=America/Toronto
        restart: unless-stopped
