name: project-manager

services:
    database:
        image: bitnami/postgresql:latest
        container_name: project-manager-database
        ports:
            - 5432:5432
        environment:
            - POSTGRESQL_DATABASE=projects
            - POSTGRESQL_PASSWORD=password
            - POSTGRESQL_POSTGRES_PASSWORD=password
            - POSTGRESQL_TIMEZONE=America/Toronto
            - POSTGRESQL_LOG_TIMEZONE=America/Toronto
        restart: unless-stopped
        volumes:
            - ./data/postgresql:/bitnami/postgresql
